### ISSUE TITLE
Support requests for coin objects

### ISSUE THREAD

**Issue by tampakis** [pulibrary/requests#402] opened 2019-03-22 10:51 UTC
Support Aeon requests for [non-voyager](https://github.com/pulibrary/requests/blob/0d58ea2e459ef5e54551750ff8bf95a8e015d67b/app/models/concerns/requests/aeon.rb#L6-L15) coin objects. Treat similar to [theses](https://github.com/pulibrary/requests/blob/6f649967e1649139a4bfd631e8a5d084a518d726/app/models/requests/requestable.rb#L35-L39), except with RBSC locations.

Initial work: https://github.com/pulibrary/requests/tree/coin-requests

**Comment by kevinreiss** [comment] 2019-03-22 14:10
@tampakis Do you have an example record for these? Other than allowed the ID pattern to pass through (which you've already done) if they are at a holding location flagged as an request aeon these should work with maybe some minor modifications related to the format getting properly mapped into Aeon.

**Comment by tampakis** [comment] 2019-03-22 14:17
All of the coins will have holdings hash like this:
```
      {
        "numismatics" => {
          "location" => "Rare Books and Special Collections",
          "library" => "Rare Books and Special Collections - Numismatics Collection",
          "location_code" => "num",
          "call_number" => "Coin #",
          "call_number_browse" => "Coin #"
        }
      }
```
The [num location code](https://bibdata.princeton.edu/locations/holding_locations/num) is already designated as an aeon location.

**Comment by hackmastera** [comment] 2020-05-12 15:35
related to or maybe duplicate of #539?

**Comment by kevinreiss** [comment] 2020-05-12 20:37
It's a duplicate. We will finish the other one.

**Closed by kevinreiss** 2020-05-12 20:37 UTC
Labels: numismatics
