### ISSUE TITLE
On Shelf Titles Highlight stackmap link

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/requests#75] opened 2017-02-08 16:10 UTC
On shelf titles should clearly route the user to the stackmap link and NOT display a pickup list widget. Example ID: 10005935

**Comment by sdellis** [comment] 2017-02-08 20:16
Partial duplicate of #77

**Comment by sdellis** [comment] 2017-02-08 20:25
This already lists the stackmap link. Closing as this is already fixed by #78

**Comment by sdellis** [comment] 2017-02-08 20:30
Hmm... this may only be the case when it's requestable.traceable. Going to add another method for the stackmap url to display if on_shelf.

**Closed** 2017-02-08 21:17 UTC
